### ISSUE TITLE
The preset buttons between the main tag panels and the all tags panel are not working

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/iD#2253]
The preset buttons for things like phone/web/wikipedia etc, that should add the relevant tag panel for input are not working in iD 1.4 on osm.org.

When they are clicked nothing happens and a js exception is thrown `TypeError: context.presets(...) is not a function`.
