### PR TITLE
Fix the content of combobox when the display label is set

### LINKED ISSUE #9159: Combobox for "more fields" broken
Affected is the development branch. See 
image

Most likely a regression in https://github.com/openstreetmap/iD/commit/4770dc8773b3aa418b200f5fa035f0ec4d602c6e

### PR DESCRIPTION
**Pull request by diana-nicolae**
Fixes #9159

The display field is not a function, it contains html.

### CODE REVIEW

File: modules/ui/combobox.js [hunk 1]
```diff
@@ -7,8 +7,7 @@ import { utilGetSetValue, utilRebind, utilTriggerEvent } from '../util';
 // It is keyed on the `value` of the entry. Data should be an array of objects like:
 //   [{
 //       value:   'string value',  // required
-//       display: 'label function' // optional, if present will be called with d3 selection
-//                                              to modify/append, see localizer's t.append
+//       display: 'label html'     // optional
```
Comment (tyrasd) [inline modules/ui/combobox.js:10]: thanks for the pull request, but this property was actually changed from containing html to a callback function in 8f79932ab1259267560541bbef2ae290d68d42e6 in order to prevent possible html injection into UI fields. see also https://github.com/openstreetmap/iD/wiki/How-to-use-iD%27s-localizer-module#use-tappendstringid-for-adding-text-with-locale-info

Comment (tyrasd) [reply modules/ui/combobox.js:10]: PS: I'm working on a "proper" fix for this bug right now.
